### ISSUE TITLE
您好！想问一下目前如果注重运行速度的话，NR-PCQA中是不是还是作者的3D-NSS比较独一档

### ISSUE THREAD

**Issue by lilrookie76** [zzc-1998/Point-cloud-quality-assessment#1]
调研了一圈发现好像大多数相关工作都不太注重这个，谢谢，希望能得到您的回复

**Comment by zzc-1998** [comment]
感谢你的提问，现在的大部分工作还是比较关注性能的，所以大部分作者并没有公开自己模型的推理速度。3d-nss也只是在与一些比较经典的全参考算法进行推理速度的比较中占优，至于NR-PCQA中有没有推理更快的还需要进行实际的测试与比较。

**Comment by lilrookie76** [comment]
> 速度

感谢您的回答，谢谢！

**Comment by jy-hh** [comment]
您好，想问一下MM-PCQA中的get_projections.py文件，我在运行时，生成的投影图片是相同的，没有经过旋转，尝试修改也没能解决，您知道该如何修改吗？

**Comment by zzc-1998** [comment]
> 您好，想问一下MM-PCQA中的get_projections.py文件，我在运行时，生成的投影图片是相同的，没有经过旋转，尝试修改也没能解决，您知道该如何修改吗？

请到另外一个issue查看
https://github.com/zzc-1998/Point-cloud-quality-assessment/issues/2
