### ISSUE TITLE
about pqanet

### ISSUE THREAD

**Issue by yokeno1** [zzc-1998/Point-cloud-quality-assessment#3]
hi，Dr. Zhang, seeing the results of pqanet reproduced in your other papers, I would like to ask how to set the distortion type on the sjtu-pcqa dataset

**Comment by zzc-1998** [comment]
Hello, yokeno,
Just set the mixed distortion type as an independent separate distortion type.

Besides, I just found your work about `baseline_for_PCQA', which is quite interesting.
May I suggest you add another NR-PCQA method from one of the early works at https://github.com/zzc-1998/NR-3DQA ?

Best Regards,
Zicheng

**Comment by yokeno1** [comment]
Thanks very much！
 I will reproduce more pcqa methods in my spare time

**Comment by yokeno1** [comment]
Sorry to bother you again. In the reproduction of pqanet, I divided SJTU-PCQA into seven types of distortion input distortion classification networks. I tried various combinations of hyperparameters but couldn't achieve convergence. Can you share some of your configurations

**Comment by zzc-1998** [comment]
Hello, 
Maybe asking the author of PQA-net would help?
This is the official repo https://github.com/qdushl/PQA-Net
